### ISSUE TITLE
Update Feliz.UseListener dependency to enable F# 5 builds

### ISSUE THREAD

**Issue by enriquein** [Zaid-Ajaj/Feliz.Router#33]
Would it be possible to update the dependency on Feliz.UseListener to 0.6.3? There doesn't seem to be any breaking changes from 0.6.1 as both minor version bumps were done to update Feliz.UseListener's dependencies. Right now I'm having issues with the F# 5 compiler because it seems to not want to recognize the library is installed because Feliz.UseListener's FSharp.Core dependency is invalid: 

`Detected package version outside of dependency constraint: Feliz.UseListener 0.6.1 requires FSharp.Core (>= 4.7.2 && < 5.0.0) but version FSharp.Core 5.0.0 was resolved.`

I would do it myself and submit a PR, but I have no idea how to update a project using paket in order to make it update a dependency. Also I don't know how comfortable you'd be with an outsider submitting changes to dependencies and such.

Thanks for this awesome routing alternative, btw.

**Comment by enriquein** [comment]
Please disregard. After upgrading to Fable 3 yesterday I was able to build the project without issues.

**Comment by Zaid-Ajaj** [comment]
Thanks for letting me know! I was going to check out the problem today but glad to hear it is resolved 😄

**Comment by enriquein** [comment]
I think it could be useful to keep in mind for when F# 5 features are officially supported by the Fable compiler, though. Right now it seems the Fable 3 tooling is (correctly) forcing the use of the F# 4.7 compiler.

**Comment by Zaid-Ajaj** [comment]
I think F# 5 is actually supported by Fable, new features like string interpolation and open static classes should just work
