### ISSUE TITLE
Errors with compiling, reason unclear

### ISSUE THREAD

**Issue by reinux** [Zaid-Ajaj/Feliz.Router#36]
I hate raising these kinds of issues since there's always a good chance it's something on my end, but Nagareyama doesn't seem to want to compile Feliz.

I'm using it in an otherwise barebones project. VS doesn't report any errors, but `dotnet fable` does. I get about 50 of these errors. Happens even without any references to Feliz.Router in code.

Fable 3.1.5, latest Feliz.Router.

Any idea what it could be?

```
/.fable/Feliz.Router.3.5.0/Router.fs(950,9): (950,41) error FSHARP: This expression was expected to have type
    'Cmd<'Msg>'
but here has type
    ''a list'     (code 1)
/.fable/Feliz.Router.3.5.0/Router.fs(953,9): (953,54) error FSHARP: This expression was expected to have type
    'Cmd<'Msg>'
but here has type
    ''a list'     (code 1)
```

**Comment by reinux** [comment]
Ah, it doesn't like the current prerelease of Fable.Elmish.React or Fable.Elmish.Browser (v4 of either).

**Comment by Zaid-Ajaj** [comment]
Hi there @reinux, does downgrading Fable.Elmish solve your issue? Because I might need to publish a new version that is compatible with latest Elmish

**Comment by reinux** [comment]
Hey, sorry, I forgot to follow up on this.

Yeah, downgrading Fable.Elmish fixed it. I wasn't too sure how you might want to proceed with this, since Elmish 4 isn't complete yet.

I'm really liking the library so far, by the way!

**Comment by Zaid-Ajaj** [comment]
As of latest Feliz.Router v3.8 this problem should go away with latest Elmish. Please let me know if it persists 🙏
