### ISSUE TITLE
Navigation based on History?

### ISSUE THREAD

**Issue by 7sharp9** [Zaid-Ajaj/Feliz.Router#39]
Within Elm Navigation Package it pretty easy to navigate though history using [Navigate.back n](https://package.elm-lang.org/packages/elm/browser/latest/Browser-Navigation#back).  

Is there anything similar in Feliz.Router?

**Comment by 7sharp9** [comment]
Maybe a alias to `Browser.Dom.history.back ()` would make sense as `Router.navigateBack()`

**Comment by Zaid-Ajaj** [comment]
Should be pretty easy to implement. I'll add it soon. For now, the workaround of using main `Browser.Dom.history.back ()` should work just fine

**Comment by Zaid-Ajaj** [comment]
@7sharp9 Why close the issue? Haven't implemented the alias yet 😅

**Comment by Zaid-Ajaj** [comment]
Added `Router.navigateBack()` and `Router.navigateForward()` as of latest v3.8
