### ISSUE TITLE
Support for html 5 routing 

### ISSUE THREAD

**Issue by marcpiechura** [Zaid-Ajaj/Feliz.Router#6]
Hi,

do you have plans to support path based routes instead of hash routes? 

Thx

**Comment by Zaid-Ajaj** [comment]
Hi there! Yeah I would like to support it but I need to investigate how first :smile: Any pointers?

**Comment by marcpiechura** [comment]
I guess https://github.com/elmish/browser would be a good starting point 😃

**Comment by KittisakT** [comment]
Modifying a code on line 106 as follows seems to support both hash-based and path-based routing.

Original :
```
override this.componentDidMount() =
        let onChange (ev: _) =
            window.location.hash
            |> Router.urlSegments
            |> this.props.urlChanged
```
Modified:
```
override this.componentDidMount() =
        let onChange (ev: _) =
            match window.location.hash with
            | "" -> window.location.pathname
            | _ -> window.location.hash
            |> Router.urlSegments
            |> this.props.urlChanged
```
I am very new to F# so if the above code can be written in any better pattern, please feel free to suggest.

**Comment by Zaid-Ajaj** [comment]
@marcpiechura AFAIK Elmish navigation does not support path routing. 

@KittisakT The problem is not how to detect current path with or without the hash sign, the problem is when you navigate programmatically to a route without a hash sign, the browser will do a full server round trip causing the client to full refresh which is definitely not the expected behavior 

Any ideas on this? PR's are always welcome

**Comment by marcpiechura** [comment]
@Zaid-Ajaj I switched to Elmish Navigation for this particular reason, hence the reason for this issue ;-) 
https://elmish.github.io/browser/routing.html#Working-with-full-HTML5-and-hash-based-URLs

But I like your take on routing more, so I would switch back if possible. 
I could try to build a PR based on elmish navigation, maybe by end of next week or do you want to continue @KittisakT ?

**Comment by Zaid-Ajaj** [comment]
> based on elmish navigation

I wouldn't do that, the code base is very different and the change is very slight. You need to register some global flag such that the programmable navigation using `Router.navigate` can pick that up and decide and whether or not to include a hash sign in the beginning of the new route

**Comment by marcpiechura** [comment]
Sorry, I don’t meant literally “based on”, but  more like taking the bits that are missing for path based routes, e.g. how to update path without making a server request

**Comment by marcpiechura** [comment]
Since #7 is merged I can close this one :)
