### ISSUE TITLE
Any plans for pre-release?

### ISSUE THREAD

**Issue by Dzoukr** [Zaid-Ajaj/Feliz.Router#62]
Hello my friend,

I am playing with the latest libraries for Fable v4 (currently in pre-release state) and having Feliz.Router in project fails with:

```
.\src\SAFEr.App.Client\.fable-build\fable_modules\Feliz.Router.3.8.0\Router.fs(952,13): (952,18) error FSHARP: The value, constructor, namespace or type 'ofSub' is not defined. Maybe you want one of the following:
client:    ofMsg (code 39)
```

Is there any plan for making pre-release for this library as well?

**Comment by Zaid-Ajaj** [comment]
Hi @Dzoukr currently Feliz.Router depends on both Feliz and Fable.Elmish both of which are prerelease and beta. I would rather wait until things stablize before I start work on downstream dependencies 😄

**Comment by Dzoukr** [comment]
Sure, I fully understand! I have the same feeling about my own libraries. 😄 Thanks for all the great work, man!
