### ISSUE TITLE
Example for routing doesnt route correctly?

### ISSUE THREAD

**Issue by jkone27** [Zaid-Ajaj/Feliz.Router#66]
I am trying the routing example in the Feliz docs, but doesnt seem to route to pages when hitting different paths (/counter, /index and so on) i am using Feliz template V4..

```fsharp
    /// <summary>
    /// A React component that uses Feliz.Router
    /// to determine what to show based on the current URL
    /// </summary>
    [<ReactComponent>]
    static member Router() =

        printfn "current path %A" Router.currentPath()
        printfn "current url %A" Router.currentUrl()

        let (currentUrl, updateUrl) = React.useState(Router.currentUrl())
        
        React.router [
            router.onUrlChanged updateUrl
            router.children [
                do
                    printfn "routing to url %A" currentUrl
                match currentUrl with
                | [ ] -> Html.h1 "Index"
                | [ "hello" ] -> Components.HelloWorld()
                | [ "counter" ] -> Components.Counter()
                | _ -> Html.h1 "Not found"
            ]
        ]

```

and then main is the simple one given but replaced the router component in place of the other

```fsharp
root.render(Components.Router())
```

**Comment by jkone27** [comment]
![image](https://user-images.githubusercontent.com/10419217/221568439-a4dac449-29a1-4aed-8799-6f09d1f86ce9.png)
![image](https://user-images.githubusercontent.com/10419217/221568487-a5d87003-bbc4-4293-84f9-3376e00a5f6c.png)

**Comment by Zaid-Ajaj** [comment]
@jkone27 that is because by default, the router uses hash routing i.e. `#/counter` not, `/counter`. See [Path routing](https://github.com/Zaid-Ajaj/Feliz.Router#using-path-routes-without-hash-sign) if you want that instead

**Comment by jkone27** [comment]
Thanks!
