### ISSUE TITLE
Router gives wrong path for non-root paths if fragment is empty

### ISSUE THREAD

**Issue by cmeeren** [Zaid-Ajaj/Feliz.Router#8]
Check out https://cmeeren.github.io/Feliz.MaterialUI/#

![image](https://user-images.githubusercontent.com/7766733/68983861-6b89a000-080d-11ea-89a6-b283e67e96f4.png)

Feliz.Router seems to think that the path there is `["Feliz.MaterialUI"]`. It should be `[]`. Works fine locally when the path is root (`localhost:8080/#`). Also works fine for all other sub-pages, where the fragment is non-empty (e.g. `cmeeren.github.io/Feliz.MaterialUI/#usage/installation`).

**Comment by Zaid-Ajaj** [comment]
Can you take v1.6.0 for a spin to see if your problem is resolved? :smile:

**Comment by cmeeren** [comment]
Unfortunately not. Check out the console output when navigating: https://cmeeren.github.io/Feliz.MaterialUI

**Comment by Zaid-Ajaj** [comment]
I was doing just that. This is weird because I changed the behavior with these specs:
```fs
testCase "RouteMode affects how the URL segments are cleaned up" <| fun _ ->
    ("/some/path#", RouteMode.Hash)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output [ ] "Hash at the end means route starts there"
	
    ("/Feliz.MaterialUI/#", RouteMode.Hash)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output [ ] "Hash at the end means route starts there"

    ("/Feliz.MaterialUI#", RouteMode.Hash)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output [ ] "Hash at the end means route starts there"

    ("/some/path#/", RouteMode.Hash)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output [ ] "Hash at the end means route starts there"

    ("/some/path#", RouteMode.Path)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output ["some";"path"] "Path segments are read correctly"

    ("/Feliz.MaterialUI#", RouteMode.Path)
    ||> Router.urlSegmentsWithRouteMode
    |> fun output -> Expect.equal output [ "Feliz.MaterialUI" ] "Path segments are read correctly"
```
Are you not using the hash routing mode? I will check out your Mui docs

**Comment by cmeeren** [comment]
I'm not specifying a mode, because it seemed to default to hash. Should I explicitly specify hash mode?

**Comment by Zaid-Ajaj** [comment]
No you shouldn't, it defaults to hash mode
