### ISSUE TITLE
There should be a similar thing as navigate but returns a string

### ISSUE THREAD

**Issue by mastoj** [Zaid-Ajaj/Feliz.Router#9]
`Router.navigate` is really nice when navigating programmatically. However, it would be nice to have the same thing when setting the `href` on a `a` tag. Basically I would like to write:

```
Html.a [
    prop.href (Router.somethingLikeNavigate("apage"))
]
```

I can have a simple work around with `prop.onClick` but doesn't it make sense to have what I suggest?

**Comment by Zaid-Ajaj** [comment]
Hello @mastoj, I guess you are looking for something like `Router.format`? Should be easy to add, just copy pasting a bunch of `Router.navigate` but instead returning a string instead of command. 

Do you want to take a stab at it 🙏 ? PRs are always welcome :smile:

**Comment by mastoj** [comment]
That was what I was planning as well :). 

I just wanted to make sure it makes sense first.

**Comment by Zaid-Ajaj** [comment]
That would be really awesome :heart:
